import type {ProviderCapabilities, ProviderHealth, ProviderMedia, ProviderResult} from './provider.interface.js';
import {PublicAdapterBase, fetchJson, mediaFromUrl} from './public-adapter.js';
import {env} from '../config/env.js';
type DvidsSearchItem={id?:string;type?:string;title?:string;short_description?:string;description?:string;date?:string;date_published?:string;duration?:number;thumbnail?:string;width?:number;height?:number;url?:string}; type DvidsSearch={results?:DvidsSearchItem[]}; type DvidsFile={src?:string;type?:string;width?:number;height?:number;bitrate?:number}; type DvidsAsset={results?:DvidsSearchItem&{files?:DvidsFile[];hls_url?:string;closed_caption_urls?:Record<string,string>}};
const configured=()=>Boolean(env.DVIDS_API_KEY); const capabilities:ProviderCapabilities={search:configured(),metadata:configured(),seasons:false,episodes:false,playback:configured(),hls:false,mp4:configured(),webm:false,subtitles:configured(),audioLanguages:false};
export class DvidsAdapter extends PublicAdapterBase {
 readonly id='dvids'; readonly name='DVIDS'; readonly capabilities=capabilities;
 private url(path:string,params:Record<string,string>={}){const query=new URLSearchParams({api_key:env.DVIDS_API_KEY,...params});return `https://api.dvidshub.net/${path}?${query}`;}
 async search(query:string){if(!configured())return [];const data=await fetchJson<DvidsSearch>(this.url('search',{q:query,type:'video',max_results:'20'}));return (data.results??[]).filter(x=>x.id&&x.type==='video'&&x.title).map(x=>this.result(x));}
 private result(x:DvidsSearchItem):ProviderResult{return {providerId:this.id,externalId:x.id!,title:x.title!,description:x.description??x.short_description,mediaType:'other',licenseStatus:'authorized',licenseEvidence:'DVIDS public media API asset record',thumbnail:x.thumbnail};}
 async getTitle(id:string){if(!configured())return null;const data=await fetchJson<DvidsAsset>(this.url('asset',{id,fields:'title,description,date,date_published,duration,thumbnail'}));return data.results?.id?this.result(data.results):null;}
 async getMedia(id:string):Promise<ProviderMedia[]>{if(!configured())return [];const data=await fetchJson<DvidsAsset>(this.url('asset',{id,fields:'title,description,date,date_published,duration,thumbnail,files,closed_caption_urls'}));const asset=data.results;if(!asset?.files)return [];return asset.files.map((file,index)=>file.src?mediaFromUrl(String(index),file.src,{status:'authorized',evidence:'DVIDS public media API asset record'},{mimeType:file.type,duration:asset.duration,resolution:file.width&&file.height?`${file.width}x${file.height}`:undefined,subtitles:asset.closed_caption_urls?.webvtt?[{language:'en',url:asset.closed_caption_urls.webvtt}]:undefined}):null).filter((x):x is ProviderMedia=>Boolean(x));}
 async resolvePlayback(sourceId:string){const slash=sourceId.lastIndexOf('/');const id=slash>0?sourceId.slice(0,slash):sourceId;const index=Number(slash>0?sourceId.slice(slash+1):'NaN');const media=await this.getMedia(id);return media[Number.isInteger(index)?index:-1]?.url??null;}
 async healthCheck():Promise<ProviderHealth>{if(!configured())return {status:'not_implemented',reason:'DVIDS requires a user-supplied API key from its official API'};const started=Date.now();try{await fetchJson<DvidsSearch>(this.url('search',{q:'public',type:'video',max_results:'1'}),5000);return {status:'healthy',latency:Date.now()-started};}catch{return {status:'degraded',latency:Date.now()-started};}}
}
