import type {ProviderAdapter,ProviderCapabilities,ProviderResult} from './provider.interface.js';
const capabilities:ProviderCapabilities={search:true,metadata:true,episodes:false,playback:true,hls:false,mp4:true,subtitles:false,webhooks:false};
type IAFile={name?:string;format?:string;size?:string}; type IAMetadata={metadata?:{identifier?:string;title?:string;description?:string;year?:string;date?:string;mediatype?:string;licenseurl?:string;rights?:string};files?:IAFile[]};
export class InternetArchiveAdapter implements ProviderAdapter { readonly id='internet-archive'; readonly name='Internet Archive'; readonly capabilities=capabilities;
 async search(query:string):Promise<ProviderResult[]> { const url=`https://archive.org/advancedsearch.php?q=${encodeURIComponent(`title:(${query}) AND mediatype:movies`)}&fl[]=identifier&fl[]=title&fl[]=year&fl[]=mediatype&rows=20&output=json`; const response=await fetch(url,{signal:AbortSignal.timeout(10000)}); if(!response.ok)throw new Error(`Internet Archive search ${response.status}`); const json=await response.json() as {response?:{docs?:Array<{identifier?:string;title?:string;year?:number;mediatype?:string}>}}; return (json.response?.docs??[]).filter(x=>x.identifier&&x.title).map(x=>({providerId:this.id,externalId:x.identifier as string,title:x.title as string,year:x.year,mediaType:'movie',licenseStatus:'unknown' as const})); }
 async getTitle(id:string){const response=await fetch(`https://archive.org/metadata/${encodeURIComponent(id)}`,{signal:AbortSignal.timeout(10000)}); if(!response.ok)return null; const json=await response.json() as IAMetadata; const m=json.metadata; if(!m?.identifier||!m.title)return null; const licenseStatus=m.licenseurl?.toLowerCase().includes('creativecommons')||m.rights?.toLowerCase().includes('public domain')?'public-domain' as const:'unknown' as const; return {providerId:this.id,externalId:m.identifier,title:m.title,year:m.year?Number(m.year):undefined,mediaType:'movie' as const,licenseStatus}; }
 async getSeasons(_titleId:string){return []} async getEpisodes(_seasonId:string){return []}
 async getMedia(id:string){const metadata=await this.getMetadata(id); return (metadata.files??[]).filter(f=>/\.(mp4|webm)$/i.test(f.name??'')).map(f=>({sourceId:f.name,format:(f.name??'').split('.').pop(),licenseStatus:'unknown'}));}
 async resolvePlayback(sourceId:string){const parts=sourceId.split('/'); if(parts.length!==2)return null; const [identifier,file]=parts; const metadata=await this.getMetadata(identifier); const match=metadata.files?.find(f=>f.name===file&&/\.(mp4|webm)$/i.test(f.name??'')); return match?.name?`https://archive.org/download/${encodeURIComponent(identifier)}/${match.name.split('/').map(encodeURIComponent).join('/')}`:null; }
 async getUpdates(){return []} async healthCheck(){const started=Date.now(); try{const response=await fetch('https://archive.org/metadata/18miles',{method:'HEAD',signal:AbortSignal.timeout(5000)}); return {status:response.ok?'healthy':'degraded',latency:Date.now()-started} as const}catch{return {status:'degraded' as const,latency:Date.now()-started}}}
 private async getMetadata(id:string){const response=await fetch(`https://archive.org/metadata/${encodeURIComponent(id)}`,{signal:AbortSignal.timeout(10000)}); if(!response.ok)throw new Error(`Internet Archive metadata ${response.status}`); return await response.json() as IAMetadata; }
}
