import type {ProviderAdapter, ProviderCapabilities, ProviderHealth, ProviderMedia, ProviderResult, LicenseStatus} from './provider.interface.js';
import {fetchJson, formatFromUrl, mimeForFormat} from './provider.interface.js';

type IAFile={name?:string;format?:string;mime?:string;size?:string;length?:string;width?:number;height?:number};
type IAMetadata={metadata?:{identifier?:string;title?:string;description?:string;year?:string;date?:string;mediatype?:string;licenseurl?:string;rights?:string;creator?:string};files?:IAFile[]};
const capabilities: ProviderCapabilities={search:true,metadata:true,seasons:false,episodes:false,playback:true,hls:false,mp4:true,webm:true,subtitles:false,audioLanguages:false};
const licenseFor=(m?:IAMetadata['metadata']): {status:LicenseStatus;evidence?:string} => { const text=`${m?.licenseurl??''} ${m?.rights??''}`.toLowerCase(); if(text.includes('public domain')||text.includes('publicdomain'))return {status:'public-domain',evidence:m?.rights||m?.licenseurl}; if(text.includes('creativecommons')||text.includes('creative commons'))return {status:'open-license',evidence:m?.rights||m?.licenseurl}; return {status:'unknown',evidence:m?.rights||m?.licenseurl}; };
export class InternetArchiveAdapter implements ProviderAdapter {
 readonly id: string='internet-archive'; readonly name: string='Internet Archive'; readonly capabilities=capabilities;
 async search(query:string):Promise<ProviderResult[]> { const data=await fetchJson<{response?:{docs?:Array<{identifier?:string;title?:string;year?:number}>}}>(`https://archive.org/advancedsearch.php?q=${encodeURIComponent(`title:(${query}) AND mediatype:movies`)}&fl[]=identifier&fl[]=title&fl[]=year&rows=20&output=json`); return Promise.all((data.response?.docs??[]).filter(x=>x.identifier&&x.title).map(x=>this.getTitle(x.identifier!))).then(xs=>xs.filter((x):x is ProviderResult=>Boolean(x))); }
 async getTitle(id:string) { const data=await this.getMetadata(id); const m=data.metadata; if(!m?.identifier||!m.title)return null; const license=licenseFor(m); return {providerId:this.id,externalId:m.identifier,title:m.title,description:m.description,year:m.year?Number(m.year):undefined,mediaType:m.mediatype==='collection'?'other':'movie',licenseStatus:license.status,licenseEvidence:license.evidence} as ProviderResult; }
 async getMedia(id:string):Promise<ProviderMedia[]> { const data=await this.getMetadata(id); const license=licenseFor(data.metadata); const media=(data.files??[]).map((f):ProviderMedia|null=>{const url=f.name?`https://archive.org/download/${encodeURIComponent(id)}/${f.name.split('/').map(encodeURIComponent).join('/')}`:undefined; const detected=f.name?formatFromUrl(f.name):null; if(!detected)return null; return {sourceId:f.name??'',format:detected,mimeType:f.mime??mimeForFormat(detected),url,licenseStatus:license.status,licenseEvidence:license.evidence,duration:f.length?Number(f.length):undefined,resolution:f.width&&f.height?`${f.width}x${f.height}`:undefined};}); return media.filter((x):x is ProviderMedia=>Boolean(x&&['public-domain','open-license','authorized'].includes(x.licenseStatus))); }
 async resolvePlayback(sourceId:string) { const [identifier,...fileParts]=sourceId.split('/'); if(!identifier||fileParts.length===0)return null; const file=fileParts.join('/'); const media=await this.getMedia(identifier); return media.some(x=>x.sourceId===file)?`https://archive.org/download/${encodeURIComponent(identifier)}/${file.split('/').map(encodeURIComponent).join('/')}`:null; }
 async getSeasons(){return []} async getEpisodes(){return []} async getUpdates(){return []}
 async healthCheck():Promise<ProviderHealth>{const started=Date.now();try{const response=await fetch('https://archive.org/metadata/gov.archives.arc.49737',{signal:AbortSignal.timeout(5000)});return {status:response.ok?'healthy':'degraded',latency:Date.now()-started};}catch{return {status:'degraded',latency:Date.now()-started};}}
 private async getMetadata(id:string){return fetchJson<IAMetadata>(`https://archive.org/metadata/${encodeURIComponent(id)}`);}
}
export class PrelingerAdapter extends InternetArchiveAdapter {
 readonly id='prelinger'; readonly name='Prelinger Archives';
 async search(query:string){const records=await super.search(query);return records.filter(record=>record.externalId.toLowerCase().includes('prelinger'));}
 async getTitle(id:string){if(!id.toLowerCase().includes('prelinger'))return null;return super.getTitle(id);}
}
