import type {ProviderCapabilities, ProviderHealth, ProviderMedia, ProviderResult} from './provider.interface.js';
import {PublicAdapterBase, fetchJson, mediaFromUrl, rightsFromText} from './public-adapter.js';
import {env} from '../config/env.js';
type AnyRecord=Record<string,unknown>; const configured=()=>Boolean(env.NARA_API_KEY); const capabilities:ProviderCapabilities={search:configured(),metadata:configured(),seasons:false,episodes:false,playback:configured(),hls:false,mp4:configured(),webm:configured(),subtitles:false,audioLanguages:false};
const arrays=(value:unknown):AnyRecord[]=>{if(!value||typeof value!=='object')return [];if(Array.isArray(value))return value.filter((x):x is AnyRecord=>Boolean(x&&typeof x==='object'));const obj=value as AnyRecord;for(const key of ['results','records','objects','items','opaResponse']){const found=arrays(obj[key]);if(found.length)return found;}return [];};
const text=(value:unknown)=>typeof value==='string'?value:undefined; const firstUrl=(value:AnyRecord)=>{for(const key of ['objectUrl','fileUrl','url','uri']){const candidate=text(value[key]);if(candidate&&/^https:\/\//.test(candidate))return candidate;}return undefined;};
export class NationalArchivesAdapter extends PublicAdapterBase {
 readonly id='national-archives'; readonly name='U.S. National Archives'; readonly capabilities=capabilities;
 private url(path:string){return `https://catalog.archives.gov/api/v2/${path}`;}
 private headers(){return {'x-api-key':env.NARA_API_KEY};}
 async search(query:string){if(!configured())return [];const data=await fetchJson<AnyRecord>(`${this.url('records/search')}?q=${encodeURIComponent(query)}`,8000,this.headers());return arrays(data).map(x=>this.result(x)).filter((x):x is ProviderResult=>Boolean(x));}
 private result(x:AnyRecord):ProviderResult|null{const id=text(x.naId)??text(x.id)??text(x.identifier);const title=text(x.title)??text(x.objectTitle);if(!id||!title)return null;const rights=rightsFromText(x.useRestriction??x.rights??x.copyrightRestriction);return {providerId:this.id,externalId:id,title,description:text(x.description),year:(text(x.date)??'').match(/\d{4}/)?.[0]?Number((text(x.date)??'').match(/\d{4}/)![0]):undefined,mediaType:'documentary',licenseStatus:rights.status,licenseEvidence:rights.evidence,thumbnail:firstUrl(x)};}
 async getTitle(id:string){if(!configured())return null;const data=await fetchJson<AnyRecord>(this.url(`records/${encodeURIComponent(id)}`),8000,this.headers());return this.result(data.record&&typeof data.record==='object'?data.record as AnyRecord:data);}
 async getMedia(id:string):Promise<ProviderMedia[]>{if(!configured())return [];const data=await fetchJson<AnyRecord>(this.url(`records/${encodeURIComponent(id)}`),8000,this.headers());const root=(data.record&&typeof data.record==='object'?data.record:data) as AnyRecord;const rights=rightsFromText(root.useRestriction??root.rights??root.copyrightRestriction);return arrays(root.digitalObjects??root.objects??root.resources).map((object,index)=>{const url=firstUrl(object);return url?mediaFromUrl(String(index),url,rights):null;}).filter((x):x is ProviderMedia=>Boolean(x&&x.licenseStatus!=='unknown'));}
 async resolvePlayback(sourceId:string){const slash=sourceId.lastIndexOf('/');const id=slash>0?sourceId.slice(0,slash):sourceId;const index=Number(slash>0?sourceId.slice(slash+1):'NaN');const media=await this.getMedia(id);return media[Number.isInteger(index)?index:-1]?.url??null;}
 async healthCheck():Promise<ProviderHealth>{if(!configured())return {status:'not_implemented',reason:'National Archives Catalog API requires a user-supplied API key'};const started=Date.now();try{const response=await fetch(`${this.url('records/search')}?q=public&rows=1`,{headers:this.headers(),signal:AbortSignal.timeout(5000)});return {status:response.ok?'healthy':'degraded',latency:Date.now()-started};}catch{return {status:'degraded',latency:Date.now()-started};}}
}
