import type {ProviderCapabilities, ProviderMedia, ProviderResult, ProviderHealth} from './provider.interface.js';
import {PublicAdapterBase, fetchJson, mediaFromUrl, peerTubeRightsFromText} from './public-adapter.js';

type PTFile={fileUrl?:string;playlistUrl?:string;width?:number;height?:number;resolution?:{label?:string}};
type PTVideo={id?:number;uuid?:string;shortUUID?:string;url?:string;origin?:string;name?:string;description?:string;duration?:number;language?:{id?:string};licence?:{id?:number;label?:string};privacy?:{id?:number};state?:{id?:number};thumbnailPath?:string;thumbnails?:Array<{fileUrl?:string;width?:number;height?:number}>;files?:PTFile[];streamingPlaylists?:Array<{playlistUrl?:string;files?:PTFile[]}>};
type PTSearch={data?:PTVideo[]};

const capabilities:ProviderCapabilities={search:true,metadata:true,seasons:false,episodes:false,playback:true,hls:true,mp4:true,webm:false,subtitles:false,audioLanguages:true};
const defaultInstances=['https://peertube2.cpy.re','https://fedi.video'];
const trustedOrigins=new Set((process.env.PEERTUBE_INSTANCES??defaultInstances.join(',')).split(',').map(value=>{try{const url=new URL(value.trim());return url.protocol==='https:'?url.origin.toLowerCase():'';}catch{return '';}}).filter(Boolean));
const normalizeOrigin=(value:string)=>{try{const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password||url.port)return null;return url.origin.toLowerCase();}catch{return null;}};
export const registerPeerTubeOrigin=(value:string)=>{const origin=normalizeOrigin(value);if(origin)trustedOrigins.add(origin);return origin;};
export const isTrustedPeerTubeHost=(host:string)=>{const normalized=host.toLowerCase();return [...trustedOrigins].some(origin=>new URL(origin).hostname===normalized);};
const idOf=(video:PTVideo)=>video.uuid??(video.id!==undefined?String(video.id):'');
const originOf=(video:PTVideo)=>{const candidate=video.url??video.origin;const origin=candidate?normalizeOrigin(candidate.includes('://')?candidate:`https://${candidate}`):null;return origin??[...trustedOrigins][0]??'https://peertube2.cpy.re';};
const externalOf=(video:PTVideo)=>`${originOf(video)}|${idOf(video)}`;
const publicVideo=(v:PTVideo,allowMissingState=false)=>Boolean(idOf(v)&&v.name&&v.privacy?.id===1&&(v.state?.id===1||(allowMissingState&&v.state==null)));

export class PeerTubeAdapter extends PublicAdapterBase {
 readonly id='peertube'; readonly name='PeerTube'; readonly capabilities=capabilities;
 private async video(externalId:string){const separator=externalId.indexOf('|');if(separator<=0)return null;const origin=normalizeOrigin(externalId.slice(0,separator));const id=externalId.slice(separator+1);if(!origin||!id)return null;registerPeerTubeOrigin(origin);return fetchJson<PTVideo>(`${origin}/api/v1/videos/${encodeURIComponent(id)}`);}
 async search(query:string){const data=await fetchJson<PTSearch>(`${[...trustedOrigins][0]??'https://peertube2.cpy.re'}/api/v1/search/videos?search=${encodeURIComponent(query)}&start=0&count=20&sort=-match`);const candidates=(data.data??[]).filter(video=>publicVideo(video,true));return (await Promise.all(candidates.map(async candidate=>{const externalId=externalOf(candidate);const verified=candidate.state?.id===1?candidate:await this.video(externalId).catch(()=>null);return verified&&publicVideo(verified)?this.result(verified,externalId):null;}))).filter((value):value is ProviderResult=>Boolean(value));}
 private result(v:PTVideo,externalId=externalOf(v)):ProviderResult{registerPeerTubeOrigin(externalId.split('|')[0]);const rights=peerTubeRightsFromText(v.licence?.label);return {providerId:this.id,externalId,title:v.name!,description:v.description,mediaType:'other',licenseStatus:rights.status,licenseEvidence:rights.evidence,language:v.language?.id,thumbnail:v.thumbnails?.[0]?.fileUrl??v.thumbnailPath};}
 async getTitle(externalId:string){const v=await this.video(externalId).catch(()=>null);return v&&publicVideo(v)?this.result(v,externalId):null;}
 async getMedia(externalId:string):Promise<ProviderMedia[]>{const v=await this.video(externalId).catch(()=>null);if(!v||!publicVideo(v))return [];const rights=peerTubeRightsFromText(v.licence?.label);if(rights.status==='unknown')return [];const candidates:PTFile[]=[];for(const playlist of v.streamingPlaylists??[]){if(playlist.playlistUrl)candidates.push({playlistUrl:playlist.playlistUrl});for(const file of playlist.files??[]){if(file.playlistUrl)candidates.push({...file,fileUrl:undefined});if(file.fileUrl)candidates.push({...file,playlistUrl:undefined});}}for(const file of v.files??[]){if(file.playlistUrl)candidates.push({...file,fileUrl:undefined});if(file.fileUrl)candidates.push({...file,playlistUrl:undefined});}const seen=new Set<string>();return candidates.map((file,index)=>{const url=file.playlistUrl??file.fileUrl;if(!url||seen.has(url))return null;seen.add(url);const parsed=normalizeOrigin(url);if(parsed)registerPeerTubeOrigin(parsed);return mediaFromUrl(String(index),url,rights,{duration:v.duration,resolution:file.width&&file.height?`${file.width}x${file.height}`:file.resolution?.label,language:v.language?.id});}).filter((x):x is ProviderMedia=>Boolean(x));}
 async resolvePlayback(sourceId:string){const slash=sourceId.lastIndexOf('/');const external=slash>0?sourceId.slice(0,slash):sourceId;const index=Number(slash>0?sourceId.slice(slash+1):'NaN');const media=await this.getMedia(external);return Number.isInteger(index)?media[index]?.url??null:null;}
 async healthCheck():Promise<ProviderHealth>{const started=Date.now();try{const origin=[...trustedOrigins][0]??'https://peertube2.cpy.re';const response=await fetch(`${origin}/api/v1/videos?count=1`,{signal:AbortSignal.timeout(5000)});return {status:response.ok?'healthy':'degraded',latency:Date.now()-started};}catch{return {status:'degraded',latency:Date.now()-started};}}
}
