import {afterAll, beforeAll, describe, expect, it} from 'vitest';
import {buildApp} from '../../src/app.js';
import {upsertCatalogTitle} from '../../src/storage/catalog.js';
import type {LocalTitle} from '../../src/storage/local-store.js';
import {providers} from '../../src/providers/adapters.js';

const fixture:LocalTitle={titleId:'fixture-ia-public-domain',title:'Public Domain Archive Fixture',alternateTitles:[],type:'movie',status:'active',availableAudioLanguages:['en'],subtitleLanguages:[],providers:['internet-archive'],seasons:[{seasonId:'fixture-season-1',seasonNumber:1,episodes:[{episodeId:'fixture-episode-1',seasonNumber:1,episodeNumber:1,title:'Public Domain Episode',sources:[{id:'fixture-source',providerId:'internet-archive',sourceId:'gov.archives.arc.49737/gov.archives.arc.49737_512kb.mp4',format:'mp4',mimeType:'video/mp4',licenseStatus:'public-domain',licenseEvidence:'Internet Archive item metadata rights',availability:'available',url:'https://archive.org/download/gov.archives.arc.49737/gov.archives.arc.49737_512kb.mp4',duration:60,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()}]}]}],sources:[]};

describe('legal playback end-to-end fixture',()=>{
 const app=buildApp();
 beforeAll(async()=>{await upsertCatalogTitle(fixture);});
 afterAll(async()=>{await app.close();});
 it('resolves episode sources from the cached legal source',async()=>{const response=await app.inject('/api/episodes/fixture-episode-1/sources');expect(response.statusCode).toBe(200);expect(JSON.parse(response.body).data.sources[0].providerId).toBe('internet-archive');});
 it('resolves a legal source on cache miss without repeating provider search',async()=>{const miss:LocalTitle={...fixture,titleId:'fixture-cache-miss',title:'Cache Miss Legal Fixture',seasons:[{seasonId:'miss-season',seasonNumber:1,episodes:[{episodeId:'miss-episode',seasonNumber:1,episodeNumber:1,title:'Miss Episode',sources:[]}]}]};await upsertCatalogTitle(miss);const originals=new Map(Object.entries(providers).map(([id,provider])=>[id,provider.search]));let archiveSearches=0;const archive=providers['internet-archive'];archive.search=async()=>{archiveSearches+=1;return [{providerId:'internet-archive',externalId:'gov.archives.arc.49737',title:'Cache Miss Legal Fixture',mediaType:'movie',licenseStatus:'public-domain',licenseEvidence:'Internet Archive item metadata rights'}]};archive.getMedia=async()=>[{sourceId:'gov.archives.arc.49737_512kb.mp4',format:'mp4',mimeType:'video/mp4',url:'https://archive.org/download/gov.archives.arc.49737/gov.archives.arc.49737_512kb.mp4',licenseStatus:'public-domain',licenseEvidence:'Internet Archive item metadata rights'}];for(const [id,search] of originals)if(id!=='internet-archive')providers[id].search=async()=>[];try{const response=await app.inject('/api/titles/fixture-cache-miss/sources');expect(response.statusCode).toBe(200);expect(JSON.parse(response.body).data.sources[0].providerId).toBe('internet-archive');expect(archiveSearches).toBe(1);}finally{for(const [id,search] of originals)providers[id].search=search;}});
 it('returns validated real MP4 playback',async()=>{const response=await app.inject('/api/episodes/fixture-episode-1/playback');const body=JSON.parse(response.body);expect(response.statusCode).toBe(200);expect(body.success).toBe(true);expect(body.available).toBe(true);expect(body.playback).toMatchObject({type:'mp4',mimeType:'video/mp4',provider:'internet-archive',isMP4:true});expect(body.playback.url).toBe('https://archive.org/download/gov.archives.arc.49737/gov.archives.arc.49737_512kb.mp4');});
 it('requires Firebase auth for user routes',async()=>{expect((await app.inject('/api/user/profile')).statusCode).toBe(401);expect((await app.inject({method:'PUT',url:'/api/user/favorites',payload:{favorites:[]}})).statusCode).toBe(401);});
});
