import {normalizeTitle} from '../core/identity/normalize.js'; import {searchCatalog} from '../storage/catalog.js'; import {cacheProviderResult} from '../sync/sync.service.js'; import {TVMazeMetadataAdapter} from '../providers/tvmaze.js'; import type {ProviderAdapter, ProviderResult} from '../providers/provider.interface.js'; import {env} from '../config/env.js';
const languageWords=new Set(['ar','arabic','bn','bengali','dub','dubbed','en','english','fr','french','hi','hindi','ja','japanese','ko','korean','sub','subbed','ta','tamil','te','telugu','ur','urdu']);
export const discoveryQuery=(q:string)=>normalizeTitle(q).split(' ').filter(term=>!languageWords.has(term)).join(' ').trim()||q.trim();
export const metadataProviders:ProviderAdapter[]=[new TVMazeMetadataAdapter()];
const isProviderResult=(value:ProviderResult):value is ProviderResult=>Boolean(value&&typeof value.providerId==='string'&&typeof value.externalId==='string'&&typeof value.title==='string'&&value.title.trim());
const matchesQuery=(query:string,record:ProviderResult)=>{const terms=discoveryQuery(query).split(' ').filter(Boolean);const hay=new Set(normalizeTitle([record.title,record.originalTitle??'',...(record.aliases??[])].join(' ')).split(' '));return terms.every(term=>hay.has(term));};
const bounded=async<T>(work:Promise<T>)=>new Promise<T>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('METADATA_PROVIDER_TIMEOUT')),env.PROVIDER_TIMEOUT_MS);work.then(value=>{clearTimeout(timer);resolve(value);},error=>{clearTimeout(timer);reject(error);});});
const discoveredInFlight=new Map<string,Promise<void>>();
async function discover(query:string){const key=discoveryQuery(query);const existing=discoveredInFlight.get(key);if(existing)return existing;const work=(async()=>{const results=await Promise.allSettled(metadataProviders.filter(provider=>provider.capabilities.search&&provider.capabilities.metadata).map(provider=>bounded(provider.search(key).then(records=>({provider,records:records.filter(record=>isProviderResult(record)&&matchesQuery(query,record))})))));for(const result of results)if(result.status==='rejected')console.warn('metadata provider discovery failed',{reason:result.reason instanceof Error?result.reason.message:'unknown'});const unique=new Map<string,{provider:ProviderAdapter;record:ProviderResult}>();for(const result of results)if(result.status==='fulfilled')for(const record of result.value.records){const identity=normalizeTitle(`${record.title}|${record.year??''}|${record.mediaType}`);if(!unique.has(identity))unique.set(identity,{provider:result.value.provider,record});}await Promise.allSettled([...unique.values()].map(item=>cacheProviderResult(item.provider,item.record)));})();discoveredInFlight.set(key,work);try{await work;}finally{discoveredInFlight.delete(key);}}
export async function discoverAndCache(q:string,page=1,limit=20){await discover(q);return searchCatalog(q,page,limit)}
