import Fastify from 'fastify'; import cors from '@fastify/cors'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit'; import {z} from 'zod'; import {env} from './config/env.js'; import {firebaseConfig,firestoreConfigured} from './config/firebase.js'; import {providers} from './providers/adapters.js'; import {InternetArchiveAdapter} from './providers/internet-archive.js'; import type {ProviderAdapter} from './providers/provider.interface.js'; import {requireFirebaseUser} from './auth/firebase-auth.js'; import {FirestoreUserRepository} from './repositories/firestore-user.repository.js'; import {searchCatalog,getCatalogTitle,findCatalogEpisode} from './storage/catalog.js'; import {resolvePlayback,resolveTitlePlayback} from './playback/resolver.js';
const ok=(data:unknown,meta:Record<string,unknown>={})=>({success:true,data,meta}); const fail=(code:string,message:string)=>({success:false,error:{code,message}}); const ia=new InternetArchiveAdapter();
export function buildApp(){const app=Fastify({logger:{level:env.NODE_ENV==='production'?'info':'debug'},requestIdHeader:'x-request-id'});app.register(helmet);app.register(cors,{origin:env.CORS_ORIGIN==='*'?true:env.CORS_ORIGIN});app.register(rateLimit,{max:100,timeWindow:'1 minute'});
 app.get('/health',async()=>ok({status:'ok',timestamp:new Date().toISOString(),storage:env.STORAGE_MODE,firebaseProjectId:firebaseConfig.projectId,firestoreConfigured}));app.get('/ready',async()=>ok({status:'ready',dependencies:{storage:env.STORAGE_MODE,firebase:firestoreConfigured?'ready':'not-configured'}}));
 const search=async(req:any,reply:any)=>{const q=z.object({q:z.string().trim().min(1).max(200),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(50).default(20)}).safeParse(req.query);if(!q.success)return reply.code(400).send(fail('VALIDATION_ERROR','Invalid search parameters'));const result=await searchCatalog(q.data.q,q.data.page,q.data.limit);return ok({query:q.data.q,total:result.total,results:result.results.map(t=>({titleId:t.titleId,title:t.title,originalTitle:t.originalTitle,alternateTitles:t.alternateTitles,type:t.type,year:t.year,poster:t.poster,availableLanguages:t.availableAudioLanguages,providers:t.providers}))},{page:q.data.page,limit:q.data.limit})};app.get('/api/search',search);app.get('/api/v1/search',search);
 const title=async(req:any,reply:any)=>{const t=await getCatalogTitle(req.params.id);if(!t)return reply.code(404).send(fail('NOT_FOUND','Title not found'));return ok(t)};app.get('/api/titles/:id',title);app.get('/api/v1/titles/:id',title);
 const seasons=async(req:any)=>{const t=await getCatalogTitle(req.params.id);return ok(t?.seasons??[])};app.get('/api/titles/:id/seasons',seasons);app.get('/api/v1/titles/:id/seasons',seasons);
 const episodes=async(req:any)=>{const t=await getCatalogTitle(req.params.id);return ok(t?.seasons.flatMap(s=>s.episodes)??[])};app.get('/api/titles/:id/episodes',episodes);app.get('/api/v1/titles/:id/episodes',episodes);
 const episode=async(req:any,reply:any)=>{const e=await findCatalogEpisode(req.params.id);if(!e)return reply.code(404).send(fail('NOT_FOUND','Episode not found'));return ok({...e.episode,titleId:e.title.titleId,releases:e.episode.sources})};app.get('/api/episodes/:id',episode);app.get('/api/v1/episodes/:id',episode);
 const playback=async(req:any)=>resolvePlayback(req.params.id,typeof req.query?.audio==='string'?req.query.audio:undefined,typeof req.query?.subtitle==='string'?req.query.subtitle:undefined);app.get('/api/episodes/:id/playback',playback);app.get('/api/v1/episodes/:id/playback',playback);const titlePlayback=async(req:any)=>resolveTitlePlayback(req.params.id,typeof req.query?.audio==='string'?req.query.audio:undefined,typeof req.query?.subtitle==='string'?req.query.subtitle:undefined);app.get('/api/titles/:id/playback',titlePlayback);app.get('/api/v1/titles/:id/playback',titlePlayback);
 const sources=async(req:any)=>{const t=await getCatalogTitle(req.params.id);return ok({titleId:req.params.id,sources:t?.sources??[],episodes:t?.seasons.flatMap(s=>s.episodes.flatMap(e=>e.sources))??[]})};app.get('/api/titles/:id/sources',sources);app.get('/api/v1/titles/:id/sources',sources);
 const allProviders=()=>Object.values(providers).map(p=>p.id==='internet-archive'?ia:p as ProviderAdapter); app.get('/api/v1/providers',async()=>ok(allProviders().map(p=>({id:p.id,name:p.name,capabilities:p.capabilities}))));app.get('/api/providers',async()=>ok(allProviders().map(p=>({id:p.id,name:p.name,capabilities:p.capabilities}))));app.get('/api/v1/providers/:id/health',async(req,reply)=>{const p=(req.params as {id:string}).id==='internet-archive'?ia:providers[(req.params as {id:string}).id];if(!p)return reply.code(404).send(fail('NOT_FOUND','Provider not found'));return ok(await p.healthCheck())});app.get('/api/providers/:id/health',async(req,reply)=>{const p=(req.params as {id:string}).id==='internet-archive'?ia:providers[(req.params as {id:string}).id];if(!p)return reply.code(404).send(fail('NOT_FOUND','Provider not found'));return ok(await p.healthCheck())});
 const userRepo=new FirestoreUserRepository(); const user=async(req:any)=>{const auth=await requireFirebaseUser(req);const data=await userRepo.get(auth.uid);return ok({uid:auth.uid,email:auth.email??null,data:data??{}})};app.get('/api/user/profile',user);app.get('/api/user/favorites',user);app.get('/api/user/history',user);app.get('/api/user/settings',user);
 app.setErrorHandler((err,req,reply)=>{req.log.error({err},'request failed');const e=err as {statusCode?:number;code?:string;message?:string};return reply.code(e.statusCode??500).send(fail(e.code??'INTERNAL_ERROR',env.NODE_ENV==='production'&&(!e.statusCode||e.statusCode>=500)?'Request failed':e.message??'Request failed'))});return app}
