import Fastify from 'fastify'; import cors from '@fastify/cors'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit'; import {z} from 'zod'; import {env} from './config/env.js'; import {demoTitles} from './catalog.js'; import {providers} from './providers/adapters.js';
const ok=(data:unknown,meta:Record<string,unknown>={})=>({success:true,data,meta}); const fail=(code:string,message:string)=>({success:false,error:{code,message}});
export function buildApp(){const app=Fastify({logger:{level:env.NODE_ENV==='production'?'info':'debug'},requestIdHeader:'x-request-id'}); app.register(helmet); app.register(cors,{origin:env.CORS_ORIGIN==='*'?true:env.CORS_ORIGIN}); app.register(rateLimit,{max:100, timeWindow:'1 minute'});
 app.get('/health',async()=>ok({status:'ok',timestamp:new Date().toISOString()})); app.get('/ready',async(_r,reply)=>reply.code(200).send(ok({status:'ready',dependencies:{database:'not-configured',redis:'not-configured',opensearch:'not-configured'}})));
 app.get('/api/v1/search',async(req,reply)=>{const q=z.object({q:z.string().trim().min(1).max(200),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(50).default(20)}).safeParse(req.query); if(!q.success)return reply.code(400).send(fail('VALIDATION_ERROR','Invalid search parameters')); const term=q.data.q.toLowerCase(); const items=demoTitles.filter(t=>[t.canonicalTitle,t.originalTitle??'',...t.genres].join(' ').toLowerCase().includes(term)); return ok(items,{page:q.data.page,limit:q.data.limit,total:items.length});});
 app.get('/api/v1/titles/:id',async(req,reply)=>{const id=(req.params as {id:string}).id; const title=demoTitles.find(t=>t.id===id); if(!title)return reply.code(404).send(fail('NOT_FOUND','Title not found')); return ok(title)});
 app.get('/api/v1/titles/:id/seasons',async()=>ok([])); app.get('/api/v1/titles/:id/episodes',async()=>ok([])); app.get('/api/v1/episodes/:id/sources',async()=>ok([])); app.get('/api/v1/episodes/:id/playback',async(_req,reply)=>reply.code(404).send(fail('NOT_FOUND','Episode not found')));
 app.get('/api/v1/providers',async()=>ok(Object.values(providers).map(p=>({id:p.id,name:p.name,capabilities:p.capabilities})))); app.get('/api/v1/providers/:id',async(req,reply)=>{const p=providers[(req.params as {id:string}).id]; if(!p)return reply.code(404).send(fail('NOT_FOUND','Provider not found')); return ok({id:p.id,name:p.name,capabilities:p.capabilities})}); app.get('/api/v1/providers/:id/health',async(req,reply)=>{const p=providers[(req.params as {id:string}).id]; if(!p)return reply.code(404).send(fail('NOT_FOUND','Provider not found')); return ok(await p.healthCheck())});
 app.get('/api/v1/genres',async()=>ok([...new Set(demoTitles.flatMap(t=>t.genres))])); app.get('/api/v1/languages',async()=>ok([...new Set(demoTitles.flatMap(t=>t.languages))])); app.get('/api/v1/stats',async()=>ok({titles:demoTitles.length,providers:Object.keys(providers).length}));
 app.register(async admin=>{admin.addHook('onRequest',async(req,reply)=>{if(req.headers['x-admin-api-key']!==env.ADMIN_API_KEY)return reply.code(401).send(fail('UNAUTHORIZED','Admin authentication required'))}); admin.post('/api/v1/admin/sync',async()=>ok({queued:false,message:'Provider sync is capability-gated and must be configured with infrastructure'})); admin.post('/api/v1/admin/reindex',async()=>ok({queued:false,message:'Search reindex is available via npm run reindex'}));});
 app.setErrorHandler((err,req,reply)=>{req.log.error({err},'request failed'); return reply.code((err as any).statusCode&&Number((err as any).statusCode)<500?(err as any).statusCode:500).send(fail('INTERNAL_ERROR',env.NODE_ENV==='production'?'Request failed':err.message))}); return app;}
