import {afterEach,describe,expect,it,vi} from 'vitest';
import {unlink} from 'node:fs/promises';
import {PeerTubeAdapter} from '../../src/providers/peertube.js';
import {peerTubeRightsFromText} from '../../src/providers/public-adapter.js';
import {validateSource} from '../../src/playback/source-validation.js';
import {cacheProviderResult} from '../../src/sync/sync.service.js';
import {readCatalog} from '../../src/storage/catalog.js';
import type {LocalSource} from '../../src/storage/local-store.js';

afterEach(()=>vi.restoreAllMocks());
const detail={uuid:'5a97f2c3-1c29-446d-a52b-ace11faf47ce',name:'What is Mastodon?',description:'Public animation',privacy:{id:1},state:{id:1},licence:{label:'Attribution'},duration:120,language:{id:'en'},streamingPlaylists:[{playlistUrl:'https://fedi.video/static/streaming-playlists/hls/video/master.m3u8',files:[{fileUrl:'https://fedi.video/static/streaming-playlists/hls/video/480-fragmented.mp4',width:854,height:480}]}]};
const source=(overrides:Partial<LocalSource>={}):LocalSource=>({id:'peer-source',providerId:'peertube',sourceId:'https://fedi.video|5a97f2c3-1c29-446d-a52b-ace11faf47ce/0',format:'hls',mimeType:'application/vnd.apple.mpegurl',licenseStatus:'open-license',licenseEvidence:'Attribution',availability:'available',url:'https://fedi.video/static/streaming-playlists/hls/video/master.m3u8',...overrides});

describe('PeerTube adapter',()=>{
 it('preserves a federated origin and verifies missing search state',async()=>{const fetchSpy=vi.spyOn(globalThis,'fetch').mockImplementation(async(input)=>{const url=String(input);if(url.includes('/search/videos'))return new Response(JSON.stringify({data:[{uuid:detail.uuid,name:detail.name,url:'https://fedi.video/videos/watch/'+detail.uuid,privacy:{id:1},state:null}]}),{status:200,headers:{'content-type':'application/json'}});return new Response(JSON.stringify(detail),{status:200,headers:{'content-type':'application/json'}});});const results=await new PeerTubeAdapter().search('animation');expect(results[0]?.externalId).toBe(`https://fedi.video|${detail.uuid}`);expect(fetchSpy.mock.calls.map(call=>String(call[0]))).toContain(`https://fedi.video/api/v1/videos/${detail.uuid}`);});
 it('uses the federated external origin for metadata and extracts the HLS master before MP4',async()=>{const fetchSpy=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify(detail),{status:200,headers:{'content-type':'application/json'}}));const media=await new PeerTubeAdapter().getMedia(`https://fedi.video|${detail.uuid}`);expect(fetchSpy.mock.calls[0]?.[0]).toBe(`https://fedi.video/api/v1/videos/${detail.uuid}`);expect(media[0]).toMatchObject({format:'hls',url:detail.streamingPlaylists[0].playlistUrl,licenseStatus:'open-license'});expect(media[1]?.format).toBe('mp4');});
 it.each(['Attribution','Attribution - Share Alike','Attribution - NoDerivatives','CC BY','CC BY-SA','CC BY-ND','CC0','Public Domain'])('recognizes explicit PeerTube license %s',license=>{expect(peerTubeRightsFromText(license).status).toMatch(/open-license|public-domain/);});
 it('rejects unknown and negated licenses',()=>{expect(peerTubeRightsFromText('Some Unknown License').status).toBe('unknown');expect(peerTubeRightsFromText('Not Creative Commons').status).toBe('unknown');});
 it('accepts trusted PeerTube HTTPS media and rejects arbitrary, HTTP, and private hosts',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(null,{status:200,headers:{'content-type':'application/vnd.apple.mpegurl'}}));expect(await validateSource(source())).toMatchObject({valid:true});expect(await validateSource(source({url:'https://example.com/video.m3u8'}))).toMatchObject({valid:false,reason:'PROVIDER_IDENTITY_MISMATCH'});expect(await validateSource(source({url:'http://fedi.video/video.m3u8'}))).toMatchObject({valid:false,reason:'INSECURE_URL'});expect(await validateSource(source({url:'https://127.0.0.1/video.m3u8'}))).toMatchObject({valid:false,reason:'PRIVATE_PROVIDER_HOST'});});
 it('does not duplicate a cached PeerTube source on repeated resolution',async()=>{const file=`/tmp/peertube-dedup-${process.pid}.json`;const previous=process.env.LOCAL_STORE_FILE;process.env.LOCAL_STORE_FILE=file;await unlink(file).catch(()=>{});const record={providerId:'peertube',externalId:'https://fedi.video|dedup',title:'Dedup PeerTube Video',mediaType:'other' as const,licenseStatus:'open-license' as const,licenseEvidence:'Attribution'};const adapter=new PeerTubeAdapter();vi.spyOn(adapter,'getMedia').mockResolvedValue([{sourceId:'0',format:'hls',mimeType:'application/vnd.apple.mpegurl',url:'https://fedi.video/video/master.m3u8',licenseStatus:'open-license',licenseEvidence:'Attribution'}]);await cacheProviderResult(adapter,record);await cacheProviderResult(adapter,record);const stored=(await readCatalog()).titles.find(item=>item.title==='Dedup PeerTube Video');expect(stored?.sources).toHaveLength(1);if(previous===undefined)delete process.env.LOCAL_STORE_FILE;else process.env.LOCAL_STORE_FILE=previous;await unlink(file).catch(()=>{});});
});
